set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(RISCV_TOOLCHAIN_ROOT "$ENV{USERPROFILE}/xpack-riscv-none-elf-gcc-13.3.0-2" CACHE PATH "RISC-V GCC installation")
set(CMAKE_C_COMPILER "${RISCV_TOOLCHAIN_ROOT}/bin/riscv-none-elf-gcc.exe")
set(CMAKE_CXX_COMPILER "${RISCV_TOOLCHAIN_ROOT}/bin/riscv-none-elf-g++.exe")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_OBJCOPY "${RISCV_TOOLCHAIN_ROOT}/bin/riscv-none-elf-objcopy.exe")
set(CMAKE_OBJDUMP "${RISCV_TOOLCHAIN_ROOT}/bin/riscv-none-elf-objdump.exe")
