"""Profile expressions; numeric expected encodings remain independent of HAL."""
EXPECTED = {'adc_handle': 'hadc1', 'timer_handle': 'htim2', 'timer_enabled': 'TIM2->CR1 & TIM_CR1_CEN', 'clock': [('PLL', '(RCC->CFGR & RCC_CFGR_SWS_Msk) >> RCC_CFGR_SWS_Pos', 2),
           ('AHB', '(RCC->CFGR & RCC_CFGR_HPRE_Msk) >> RCC_CFGR_HPRE_Pos', 10),
           ('APB1', '(RCC->CFGR & RCC_CFGR_PPRE1_Msk) >> RCC_CFGR_PPRE1_Pos', 0),
           ('APB2', '(RCC->CFGR & RCC_CFGR_PPRE2_Msk) >> RCC_CFGR_PPRE2_Pos', 0),
           ('ADC1 clock', '__HAL_RCC_ADC1_IS_CLK_ENABLED()', 1),
           ('TIM2 clock', '__HAL_RCC_TIM2_IS_CLK_ENABLED()', 1),
           ('DMA2 clock', '__HAL_RCC_DMA2_IS_CLK_ENABLED()', 1)],
 'gpio': [('GPIOG clock', '__HAL_RCC_GPIOG_IS_CLK_ENABLED()', 1),
          ('PG13 output', '(GPIOG->MODER & GPIO_MODER_MODER13_Msk) >> GPIO_MODER_MODER13_Pos', 1),
          ('PG13 push-pull', '(GPIOG->OTYPER & GPIO_OTYPER_OT13_Msk) >> GPIO_OTYPER_OT13_Pos', 0),
          ('PG13 no pull', '(GPIOG->PUPDR & GPIO_PUPDR_PUPD13_Msk) >> GPIO_PUPDR_PUPD13_Pos', 0),
          ('PG13 low speed',
           '(GPIOG->OSPEEDR & GPIO_OSPEEDR_OSPEED13_Msk) >> GPIO_OSPEEDR_OSPEED13_Pos',
           0),
          ('PG13 initial', '(GPIOG->ODR & GPIO_ODR_OD13_Msk) >> GPIO_ODR_OD13_Pos', 0)],
 'led_initial': 0,
 'gpio_mode_expression': '(GPIOG->MODER >> 26) & 3',
 'gpio_mode': 1,
 'dma_remaining': 'DMA2_Stream0->NDTR',
 'measurement_quality': 2,
 'adc_vectors': [('*(unsigned short *)0x1FFF7A2C', '*(unsigned short *)0x1FFF7A2A', 3300, 30000),
                 ('*(unsigned short *)0x1FFF7A2E', '*(unsigned short *)0x1FFF7A2A', 3300, 110000)],
 'led_port': 'GPIOG',
 'led_pin': 'GPIO_PIN_13',
 'led_level': '(GPIOG->ODR >> 13) & 1'}
