set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
if(DEFINED ENV{ARM_TOOLCHAIN_ROOT})
    set(toolchain_default "$ENV{ARM_TOOLCHAIN_ROOT}")
elseif(CMAKE_HOST_WIN32)
    set(toolchain_default "$ENV{USERPROFILE}/xpack-arm-none-eabi-gcc-13.3.1-1.1")
else()
    set(toolchain_default "/opt/xpack-arm-none-eabi-gcc-13.3.1-1.1")
endif()
set(ARM_TOOLCHAIN_ROOT "${toolchain_default}" CACHE PATH "ARM GCC installation")
if(CMAKE_HOST_WIN32)
    set(tool_suffix .exe)
endif()
set(CMAKE_C_COMPILER "${ARM_TOOLCHAIN_ROOT}/bin/arm-none-eabi-gcc${tool_suffix}")

set(CMAKE_CXX_COMPILER "${ARM_TOOLCHAIN_ROOT}/bin/arm-none-eabi-g++${tool_suffix}")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
