set(BOARD "F411CE" CACHE STRING "F411CE or F401CC")
if(DEFINED BLACKPILL_CONFIGURED_BOARD AND NOT BLACKPILL_CONFIGURED_BOARD STREQUAL BOARD)
 message(FATAL_ERROR "Use a separate build directory for each BOARD")
endif()
set(BLACKPILL_CONFIGURED_BOARD "${BOARD}" CACHE INTERNAL "Configured MCU")
set_property(CACHE BOARD PROPERTY STRINGS F411CE F401CC)
if(BOARD STREQUAL "F411CE")
 set(device STM32F411xE)
 set(FLASH_SIZE 512K)
 set(RAM_SIZE 128K)
 set(profile f411ce)
elseif(BOARD STREQUAL "F401CC")
 set(device STM32F401xC)
 set(FLASH_SIZE 256K)
 set(RAM_SIZE 64K)
 set(profile f401cc)
else()
 message(FATAL_ERROR "Unknown BOARD")
endif()
configure_file(ld/stm32f4.ld.in "${CMAKE_BINARY_DIR}/firmware.ld" @ONLY)
add_executable(${PROJECT_NAME} src/main.cpp src/program.cpp src/adc_units.cpp src/platform.c src/startup.c)
set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX .elf C_STANDARD 17 CXX_STANDARD 17)
target_include_directories(${PROJECT_NAME} PRIVATE src cmsis/Core/Include cmsis/Device/Include)
target_compile_definitions(${PROJECT_NAME} PRIVATE ${device})
set(arch -mcpu=cortex-m4 -mthumb -mfloat-abi=soft)
target_compile_options(${PROJECT_NAME} PRIVATE ${arch} -g3 -fno-lto -ffunction-sections -fdata-sections -Wall -Wextra -Werror "$<$<CONFIG:Debug>:-Og>" "$<$<CONFIG:Release>:-Os>" "$<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions;-fno-rtti;-fno-threadsafe-statics>")
target_link_options(${PROJECT_NAME} PRIVATE ${arch} -nostdlib "-T${CMAKE_BINARY_DIR}/firmware.ld" -Wl,--gc-sections "-Wl,-Map=${CMAKE_BINARY_DIR}/firmware.map")
target_link_libraries(${PROJECT_NAME} PRIVATE gcc)
set_property(TARGET ${PROJECT_NAME} APPEND PROPERTY LINK_DEPENDS "${CMAKE_BINARY_DIR}/firmware.ld")
add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
 COMMAND "${CMAKE_OBJCOPY}" -O ihex "$<TARGET_FILE:${PROJECT_NAME}>" "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.hex"
 COMMAND "${CMAKE_OBJCOPY}" -O binary --gap-fill 0xFF "$<TARGET_FILE:${PROJECT_NAME}>" "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.bin"
 VERBATIM)

option(BLACKPILL_HIL "Enable GDB scenarios and offline prepare" OFF)
if(BLACKPILL_HIL)
set(Python3_FIND_REGISTRY LAST)
enable_testing()
include(modules/stm32-gdbtest/stm32_gdbtest/cmake/STM32GDBTest.cmake)
stm32_gdbtest_attach(${PROJECT_NAME} PROFILE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/hil" PROFILE "${CMAKE_CURRENT_SOURCE_DIR}/hil/profiles/${profile}.toml" MANIFEST_INPUTS "${CMAKE_BINARY_DIR}/firmware.ld" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/blackpill.cmake")
endif()
