set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/arm-gcc.cmake")
project(stm32_hwtest_blackpill LANGUAGES C CXX ASM)
set(BOARD "F411CE" CACHE STRING "F411CE or F401CC")
if(BOARD STREQUAL "F411CE")
 set(device STM32F411xE)
 set(FLASH_SIZE 512K)
 set(RAM_SIZE 128K)
 set(profile f411ce)
elseif(BOARD STREQUAL "F401CC")
 set(device STM32F401xC)
 set(FLASH_SIZE 256K)
 set(RAM_SIZE 64K)
 set(profile f401cc)
else()
 message(FATAL_ERROR "Unknown BOARD")
endif()
configure_file(ld/stm32f4.ld.in "${CMAKE_BINARY_DIR}/firmware.ld" @ONLY)
add_executable(${PROJECT_NAME} src/main.cpp src/program.cpp src/adc_units.cpp src/platform.c src/startup.c)
set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX .elf C_STANDARD 17 CXX_STANDARD 17)
target_include_directories(${PROJECT_NAME} PRIVATE src cmsis/Core/Include cmsis/Device/Include)
target_compile_definitions(${PROJECT_NAME} PRIVATE ${device})
set(arch -mcpu=cortex-m4 -mthumb -mfloat-abi=soft)
target_compile_options(${PROJECT_NAME} PRIVATE ${arch} -g3 -fno-lto -ffunction-sections -fdata-sections -Wall -Wextra -Werror "$<$<CONFIG:Debug>:-Og>" "$<$<CONFIG:Release>:-Os>" "$<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions;-fno-rtti;-fno-threadsafe-statics>")
target_link_options(${PROJECT_NAME} PRIVATE ${arch} -nostdlib "-T${CMAKE_BINARY_DIR}/firmware.ld" -Wl,--gc-sections "-Wl,-Map=${CMAKE_BINARY_DIR}/firmware.map")
target_link_libraries(${PROJECT_NAME} PRIVATE gcc)
set_property(TARGET ${PROJECT_NAME} APPEND PROPERTY LINK_DEPENDS "${CMAKE_BINARY_DIR}/firmware.ld")
enable_testing()
include(modules/stm32-gdbtest/stm32_gdbtest/cmake/STM32GDBTest.cmake)
stm32_gdbtest_attach(${PROJECT_NAME} PROFILE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/hil" PROFILE "${CMAKE_CURRENT_SOURCE_DIR}/hil/profiles/${profile}.toml" MANIFEST_INPUTS "${CMAKE_BINARY_DIR}/firmware.ld" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/blackpill.cmake")
